"""Robust submission updater — handles both .click() and JS click."""
import os
import sys
from playwright.sync_api import sync_playwright

VIDEO_URL = "https://raw.githubusercontent.com/CallmeFull/agentmint/main/demo/walkthrough.mp4"
GITHUB_URL = "https://github.com/CallmeFull/agentmint"
DEMO_URL = "https://tiger-cleaning-clothes-satisfy.trycloudflare.com"
CONTRACT = "0x8cF902DF7f4E353B02886538d30bF5F170a70B1f"
WALLET = "0x545CD9428626e3465b1862CF2c4a8D695FdAd1AF"

DESC_TEXT = (
    "AgentMint — Mint intelligent, evolving AI agents as on-chain iNFTs on 0G Galileo testnet.\n\n"
    "What it does:\n"
    "- Describe an AI personality in a few words\n"
    "- Personality is generated by 0G Compute (qwen2.5-omni-7b) and stored on 0G Storage (Merkle root on-chain)\n"
    "- A soulbound + transferable ERC-721 iNFT is minted with the personality hash in its metadata\n"
    "- Anyone can chat with the agent through 0G Compute (real-time, paid per token)\n\n"
    "What makes it different (v2 — Evolving iNFTs):\n"
    "- Each agent is an evolving NFT: every chat increments its on-chain summon count\n"
    "- 4 milestones: Initiate (0) → Curious (5) → Wise (15) → Ancient (40) chats\n"
    "- Level system: floor(sqrt(chats/2)) + 1, displayed with XP bar\n"
    "- On-chain voting: thumbs up/down updates a signed score that affects rarity\n"
    "- Rarity score: Common → Uncommon → Rare → Legendary based on level + votes\n"
    "- Personality hash stored on-chain so the agent's soul is verifiable forever\n\n"
    "Tech stack:\n"
    "- Smart contract: Solidity 0.8.24 + OpenZeppelin ERC721URIStorage + viaIR, deployed on 0G Galileo (chainId 16602)\n"
    "- Storage: 0G Storage (Merkle tree root hashes written on-chain)\n"
    "- Compute: 0G Compute broker (qwen2.5-omni-7b via compute-network-6.integratenetwork.work)\n"
    "- Frontend: Next.js 14, ethers v6, dark cyberpunk UI\n"
    "- Tunnel: cloudflared (demo URL above)\n\n"
    "Contract address (0G Galileo): " + CONTRACT + "\n"
    "Deployer / Sub-account owner: " + WALLET + "\n"
    "GitHub: " + GITHUB_URL + "\n"
    "Demo video: " + VIDEO_URL + "\n\n"
    "Tested end-to-end: a pirate agent was minted, chatted with 7+ times via 0G Compute, reached Level 3 with the 'Wise' milestone, and got 3 upvotes. All on-chain and on testnet. Build with: npm install && npm run dev."
)

def main():
    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=True)
        ctx = browser.new_context(
            viewport={"width": 1280, "height": 900},
            storage_state=".auth_cookies.json",
        )
        page = ctx.new_page()
        page.set_default_timeout(15000)
        page.goto("https://0g.ai/arena/h/zero-cup/submit", wait_until="domcontentloaded", timeout=30000)
        page.wait_for_timeout(3000)
        print("URL:", page.url)
        print("Title:", page.title())

        # Verify auth — look for sign-in form
        if "Sign in" in page.content() or "sign in" in page.title().lower():
            print("⚠ Auth expired — need to re-login")
            page.screenshot(path="submit_v2_auth_expired.png", full_page=True)
            browser.close()
            sys.exit(2)

        # Fill description
        desc = page.locator('textarea[name*="description" i]').first
        desc.wait_for(state="visible", timeout=10000)
        desc.fill(DESC_TEXT)
        print("✓ Filled description")
        page.wait_for_timeout(500)

        # Fill video URL
        video = page.locator('input[type="url"]').first
        if video.is_visible(timeout=2000):
            video.fill(VIDEO_URL)
            print("✓ Filled video URL")
        page.wait_for_timeout(500)

        page.screenshot(path="submit_v2_filled.png", full_page=True)

        # Click submit — try several selectors
        clicked = False
        for sel in [
            'button:has-text("Update submission")',
            'button:has-text("Update")',
            'button:has-text("Save")',
            'button:has-text("Submit")',
            'button[type="submit"]',
        ]:
            try:
                btn = page.locator(sel).first
                if btn.is_visible(timeout=2000):
                    btn.scroll_into_view_if_needed()
                    btn.click(force=True, timeout=5000)
                    print(f"✓ Clicked: {sel}")
                    clicked = True
                    break
            except Exception as e:
                print(f"  {sel}: {str(e)[:80]}")

        if not clicked:
            print("⚠ No submit button found via Playwright — trying JS click")
            try:
                page.evaluate("""() => {
                    const btns = document.querySelectorAll('button');
                    for (const b of btns) {
                        const t = b.textContent || '';
                        if (t.match(/update|save|submit/i)) {
                            b.click();
                            return t.trim();
                        }
                    }
                    return null;
                }""")
                print("✓ JS-clicked submit")
            except Exception as e:
                print(f"  JS click failed: {e}")

        page.wait_for_timeout(4000)
        page.screenshot(path="submit_v2_done.png", full_page=True)
        print("✓ Done")
        browser.close()

if __name__ == "__main__":
    main()
